// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string):Promise<main.FileResult>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetCurrentFile():Promise<string>;

export function IsMarkdownFile(arg1:string):Promise<boolean>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function NewFile():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<main.FileResult>;

export function SaveFile(arg1:string):Promise<main.FileResult>;

export function SaveFileDialog():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<main.FileResult>;
