// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function ExportToHTML(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToHTML'](arg1, arg2, arg3);
}

export function ExportToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToPDF'](arg1, arg2, arg3);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function IsMarkdownFile(arg1) {
  return window['go']['main']['App']['IsMarkdownFile'](arg1);
}

export function IsWindowMaximised() {
  return window['go']['main']['App']['IsWindowMaximised']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function MinimiseWindow() {
  return window['go']['main']['App']['MinimiseWindow']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function StartDrag() {
  return window['go']['main']['App']['StartDrag']();
}

export function ToggleMaximiseWindow() {
  return window['go']['main']['App']['ToggleMaximiseWindow']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
