// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function CreateFile(arg1:string):Promise<main.FileResult>;

export function ExportToHTML(arg1:string,arg2:string,arg3:string):Promise<main.FileResult>;

export function ExportToPDF(arg1:string,arg2:string,arg3:string):Promise<main.FileResult>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetCurrentFile():Promise<string>;

export function GetWindowPos():Promise<number|number>;

export function IsMarkdownFile(arg1:string):Promise<boolean>;

export function IsWindowMaximised():Promise<boolean>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function MinimiseWindow():Promise<void>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function NewFile():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenNewWindow():Promise<void>;

export function ReadFile(arg1:string):Promise<main.FileResult>;

export function SaveFile(arg1:string):Promise<main.FileResult>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function ToggleMaximiseWindow():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<main.FileResult>;
